### PR TITLE
Add another row for apps only

### PR DESCRIPTION
**Pull request by colemamd**
I wanted to be able to add more apps, so I added another row on the bottom for more apps to be added, if desired. I'd like for it to be able to be dynamically updated, but I'm not sure how to do that. If you can point me in the right direction I can work on it.

### CODE REVIEW

**Comment by colemamd** [comment]
Just updated the code to include dynamically changing card size based on number of apps, up to 16 apps possible.

**Comment by HABuild** [comment]
So I just dropped your earlier 4 app one into my roku dir and it worked fine so far after adding to card config. I haven't tried the multi app version. 
However I wonder if you could explain the function of the apps. It only only offers to download the image (on right click) from the lovelace overview for me. I am perhaps missing something in my config, I don't have a Roku. In which case a tap_action>url would be better for me, but not important.


card config.
``` 
apps:
  - icon: /local/icons/netflix.webp
    id: Netflix
    tap_action: url
  - icon: /local/icons/emby.webp
    id: Emby
  - icon: /local/icons/emby.webp
    id: Emby
  - icon: /local/icons/emby.webp
    id: Emby
    tap_action:
      url: 'http://www.netflix.com'

```

**Comment by colemamd** [comment]
The apps show the apps (that are installed on your Roku) that you have identified in your config, and allow you to launch them (or whatever the tap_action is defined as). Haven't seen the .webp extension before, my icons are all .jpg or .png. Maybe that's it?
Not sure if having a Roku or not will effect the operation, I assume if everything else works fine, then it should.

**Comment by HABuild** [comment]
Ahh I see. The tap_action doesn't work at all. I don't think icon.extension will matter. I don't have any config relating to app > id: without having a roku installed. no big deal anyway. I was just using the card for a quick dirty edit to a mqtt remote. Thanks.

**Comment by colemamd** [comment]
Yeah, that's why. You have to have some apps (or the component needs to "see" some apps) for that part to work. If null it won't use them

**Comment by iantrich** [comment]
You need to update the actual files in /src otherwise there is no way to continue your work

**Comment by iantrich** [comment]
Also, did a rewrite of a lot of stuff over the weekend, so you'll likely want to start with a freshly pulled version from master

**Comment by Justahobby01** [comment]
Could I have an example or explanation of how I implement the extra app row? Adding a 5th app to my app list doesn't seem to do anything.

**Comment by iantrich** [comment]
You don't. This was not merged

**Comment by Justahobby01** [comment]
Ah, ok. Thank you.

**Pull request closed without merging**
